spring:
  application:
    name: fBook

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 141306
    hikari:
      schema: fbook

  flyway:
    schemas: fbook
