spring:
  application:
    name: fBook

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 141306
    hikari:
      schema: fbook

  flyway:
    schemas: fbook

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 1MB